# This is a basic workflow to help you get started with Actions
name: Create PDF Document

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: docker.io/asciidoctor/docker-asciidoctor

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Convert AsciiDoc to PDF
        run: asciidoctor-pdf -a pdf-theme=resume -a pdf-themesdir=themes resume.adoc

      # Upload
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Book # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: resume.pdf
